http-server:
  host: localhost
  port: 1337
  request-timeout: 5s
  session-timeout: 60s
data-source:
  url: postgres://sponge:bob@localhost:6767/url-shortener?sslmode=disable
migrations:
  path: file://migrations
