version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sponge
      POSTGRES_PASSWORD: bob
      POSTGRES_DB: url-shortener
    ports:
      - "6767:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
